# Generated by Django 4.1.7 on 2023-02-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speeding_fines_app', '0002_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
